import {StyleSheet} from 'react-native';

export const exampleTheme = {
  background: '#FFF8E8',
  backgroundSoft: '#FBF4E5',
  primary: '#659287',
  foreground: '#FFFFFF',
  textPrimary: '#666666',
  textSecondary: '#848282',
  textHint: '#B3B3B3',
  brandText: '#767676',
  videoBackground: '#252525',
  surface: '#FFFFFF',
  inputBorder: '#E1DBCF',
  failure: '#B42318',
  warning: '#E68A35',
};

export const uiStyles = StyleSheet.create({
  configureRoot: {
    flex: 1,
    backgroundColor: exampleTheme.background,
  },
  configureBody: {
    width: '100%',
    maxWidth: 460,
    alignSelf: 'center',
    gap: 16,
    paddingHorizontal: 24,
    paddingTop: 0,
    paddingBottom: 32,
  },
  header: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  brandWrap: {
    flex: 1,
    minWidth: 0,
  },
  brand: {
    color: exampleTheme.brandText,
    fontSize: 22,
    fontWeight: '700',
    letterSpacing: 0,
  },
  brandSubtitle: {
    color: exampleTheme.textHint,
    fontSize: 12,
    fontWeight: '500',
    letterSpacing: 0,
    marginTop: 2,
  },
  headerTitle: {
    flex: 1,
    color: exampleTheme.brandText,
    fontSize: 22,
    fontWeight: '700',
  },
  headerAction: {
    minHeight: 40,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: exampleTheme.primary,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerActionText: {
    color: exampleTheme.primary,
    fontSize: 13,
    fontWeight: '500',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: exampleTheme.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backButtonText: {
    color: exampleTheme.primary,
    fontSize: 32,
    lineHeight: 34,
  },
  fieldRow: {
    flexDirection: 'row',
    gap: 12,
  },
  inputWrap: {
    flex: 1,
    minHeight: 74,
    borderRadius: 20,
    backgroundColor: exampleTheme.surface,
    paddingHorizontal: 18,
    paddingTop: 10,
    paddingBottom: 10,
  },
  inputLabel: {
    color: exampleTheme.textSecondary,
    fontSize: 13,
    fontWeight: '500',
    marginBottom: 4,
  },
  input: {
    minHeight: 34,
    color: exampleTheme.textPrimary,
    fontSize: 13,
    padding: 0,
  },
  multilineInput: {
    minHeight: 72,
    textAlignVertical: 'top',
  },
  choice: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: exampleTheme.inputBorder,
    backgroundColor: exampleTheme.surface,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  choiceSelected: {
    borderColor: 'rgba(101,146,135,0.36)',
    backgroundColor: 'rgba(101,146,135,0.15)',
  },
  choiceText: {
    color: exampleTheme.textSecondary,
    fontSize: 13,
    fontWeight: '700',
  },
  choiceTextSelected: {
    color: exampleTheme.primary,
  },
  choiceRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  primaryButton: {
    minHeight: 56,
    borderRadius: 30,
    backgroundColor: exampleTheme.primary,
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
    paddingVertical: 16,
  },
  dangerButton: {
    backgroundColor: '#F87171',
  },
  disabledButton: {
    backgroundColor: exampleTheme.textHint,
  },
  primaryButtonText: {
    color: exampleTheme.foreground,
    fontSize: 16,
    fontWeight: '600',
  },
  outlineButton: {
    minHeight: 52,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(101,146,135,0.18)',
    backgroundColor: 'rgba(255,255,255,0.90)',
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 14,
  },
  compactOutlineButton: {
    minWidth: 84,
    minHeight: 28,
    borderRadius: 10,
    borderColor: exampleTheme.primary,
    backgroundColor: 'transparent',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  disabledOutlineButton: {
    borderColor: exampleTheme.textHint,
  },
  outlineButtonText: {
    color: exampleTheme.primary,
    fontSize: 12,
    fontWeight: '600',
  },
  disabledText: {
    color: exampleTheme.textHint,
  },
  stageControlButton: {
    minHeight: 56,
    borderRadius: 30,
    backgroundColor: exampleTheme.primary,
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingVertical: 16,
  },
  stageControlDanger: {
    backgroundColor: '#F87171',
  },
  stageControlSurface: {
    backgroundColor: exampleTheme.surface,
  },
  stageControlWarning: {
    backgroundColor: '#E68A35',
  },
  stageControlDisabled: {
    backgroundColor: exampleTheme.textHint,
  },
  stageControlText: {
    color: exampleTheme.foreground,
    fontSize: 16,
    fontWeight: '600',
  },
  stageControlSurfaceText: {
    color: exampleTheme.primary,
  },
  textLink: {
    minHeight: 36,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  textLinkText: {
    color: exampleTheme.textSecondary,
    fontSize: 13,
    fontStyle: 'italic',
    fontWeight: '700',
    textDecorationLine: 'underline',
  },
  statusText: {
    color: exampleTheme.textPrimary,
    fontSize: 14,
    lineHeight: 20,
  },
  diagnosticsPanel: {
    gap: 8,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(101,146,135,0.18)',
    backgroundColor: 'rgba(255,255,255,0.88)',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  diagnosticsTitle: {
    color: exampleTheme.brandText,
    fontSize: 13,
    fontWeight: '700',
  },
  diagnosticsLine: {
    color: exampleTheme.textPrimary,
    fontSize: 12,
    lineHeight: 17,
  },
  scannerLead: {
    color: exampleTheme.textSecondary,
    fontSize: 14,
    lineHeight: 22,
  },
  scannerFrame: {
    aspectRatio: 1,
    borderRadius: 30,
    overflow: 'hidden',
    backgroundColor: exampleTheme.videoBackground,
  },
  scannerCamera: {
    flex: 1,
  },
  scannerPlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: exampleTheme.videoBackground,
  },
  scannerPlaceholderText: {
    color: exampleTheme.foreground,
    fontSize: 14,
    fontWeight: '600',
  },
  scannerBadge: {
    position: 'absolute',
    top: 14,
    alignSelf: 'center',
    borderRadius: 999,
    backgroundColor: 'rgba(0,0,0,0.46)',
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  scannerBadgeText: {
    color: exampleTheme.foreground,
    fontSize: 12,
    fontWeight: '700',
  },
  videoStage: {
    flex: 1,
    backgroundColor: exampleTheme.videoBackground,
  },
  videoContent: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stageOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.08)',
  },
  stageBadge: {
    minHeight: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(0,0,0,0.46)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 16,
  },
  stageLabel: {
    color: exampleTheme.foreground,
    fontSize: 14,
    fontWeight: '600',
  },
  topBar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
    elevation: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    backgroundColor: exampleTheme.background,
  },
  topBackButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  topBackText: {
    color: exampleTheme.primary,
    fontSize: 32,
    lineHeight: 34,
  },
  topTitle: {
    color: exampleTheme.primary,
    fontSize: 14,
    fontWeight: '600',
  },
  topTitleWrap: {
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
  },
  topActions: {
    flexDirection: 'row',
    alignItems: 'center',
    flexShrink: 0,
    gap: 8,
    zIndex: 1,
  },
  noPointerEvents: {
    pointerEvents: 'none',
  },
});
